// ─── ONBOARDING TOUR TEXT (Level 3 — Real Actions) ──────────────────────────

export const TOUR_TEXT = {
  en: {
    welcomeTitle: "ContentStudio AI \u2014 Multi-Channel Content Generator",
    welcomeBody: "Generate optimized marketing content for Instagram, Twitter/X, LinkedIn, and Facebook. Choose from 5 tones and 5 formats, get AI-generated copy with color palettes and DALL-E image prompts.\n\nLet me show you how — with real actions!",
    startTour: "Start Tour \u2192",
    skipTour: "Skip",
    skipLabel: "Skip Tour",
    tryIt: "Try it \u2192",
    next: "Next \u2192",
    generate: "Generate \u2192",
    finish: "Finish Tour \u2713",
    restartTour: "Restart Tour",
    explore: "Start Creating",
    watchAction: "Watch the magic...",
    step1Title: "Describe Your Brand",
    step1Body: "Watch as I type a sample brand description into the textarea. The more detail you give, the better the generated content.",
    step2Title: "Choose a Platform",
    step2Body: "I'll select Instagram as the target platform. Each platform has optimized dimensions and formats.",
    step3Title: "Tone + Format",
    step3Body: "Selecting 'Professional' tone. Pick from 5 tones and 5 formats to shape your content style.",
    step4Title: "Generate Content",
    step4Body: "Now watch as I click Generate. The AI analyzes your brand and produces optimized copy, hashtags, and DALL-E prompts.",
    step5Title: "Preview Results",
    step5Body: "Here are the generated headline, body, CTA, and hashtags. Each card is individually copyable.",
    step6Title: "Color Palette + DALL-E",
    step6Body: "The Visual tab shows your auto-generated color palette and a ready-to-use DALL-E 3 image prompt.",
    step7Title: "A/B Variants",
    step7Body: "Generate alternative versions to compare headlines, CTAs, and body copy side by side.",
    step8Title: "Content Calendar",
    step8Body: "Switch to the Calendar tab to plan and schedule your content across the week. Drag and drop content into time slots.",
    step9Title: "Template Library",
    step9Body: "Save your current settings as templates for quick reuse. Load templates to instantly populate brand, platform, tone, and format.",
    completeTitle: "You're All Set!",
    completeBody: "You've seen real content generation, A/B variants, the calendar planner, and template management. Explore history, export as JSON or Markdown, and add your Claude API key for real AI-powered generation.",
    pagesVisited: "Features Explored",
    demosPlayed: "Real Actions",
    featuresExplored: "Steps Completed",
    sampleBrand: "Meditation app for professionals with adaptive AI that reduces stress in 10 minutes a day, featuring personalized sessions and progress tracking",
    stepOf: (c, t) => `${c} / ${t}`,
  },
  es: {
    welcomeTitle: "ContentStudio AI \u2014 Generador de Contenido Multicanal",
    welcomeBody: "Genera contenido de marketing optimizado para Instagram, Twitter/X, LinkedIn y Facebook. Elige entre 5 tonos y 5 formatos, obt\u00e9n copy generado por IA con paletas de colores y prompts para DALL-E.\n\n\u00a1D\u00e9jame mostrarte c\u00f3mo \u2014 con acciones reales!",
    startTour: "Iniciar Tour \u2192",
    skipTour: "Omitir",
    skipLabel: "Omitir Tour",
    tryIt: "Probar \u2192",
    next: "Siguiente \u2192",
    generate: "Generar \u2192",
    finish: "Finalizar Tour \u2713",
    restartTour: "Reiniciar Tour",
    explore: "Empezar a Crear",
    watchAction: "Observa la magia...",
    step1Title: "Describe tu Marca",
    step1Body: "Observa c\u00f3mo escribo una descripci\u00f3n de marca en el \u00e1rea de texto. Mientras m\u00e1s detalle des, mejor ser\u00e1 el contenido generado.",
    step2Title: "Elige una Plataforma",
    step2Body: "Seleccionar\u00e9 Instagram como plataforma objetivo. Cada plataforma tiene dimensiones y formatos optimizados.",
    step3Title: "Tono + Formato",
    step3Body: "Seleccionando tono 'Profesional'. Elige entre 5 tonos y 5 formatos para dar forma a tu estilo de contenido.",
    step4Title: "Generar Contenido",
    step4Body: "Ahora observa c\u00f3mo hago clic en Generar. La IA analiza tu marca y produce copy optimizado, hashtags y prompts para DALL-E.",
    step5Title: "Vista Previa de Resultados",
    step5Body: "Aqu\u00ed est\u00e1n el headline, cuerpo, CTA y hashtags generados. Cada tarjeta se puede copiar individualmente.",
    step6Title: "Paleta de Colores + DALL-E",
    step6Body: "La pesta\u00f1a Visual muestra tu paleta de colores auto-generada y un prompt listo para usar con DALL-E 3.",
    step7Title: "Variantes A/B",
    step7Body: "Genera versiones alternativas para comparar headlines, CTAs y body copy lado a lado.",
    step8Title: "Calendario de Contenido",
    step8Body: "Cambia a la pesta\u00f1a Calendario para planificar y programar tu contenido durante la semana. Arrastra y suelta contenido en los horarios.",
    step9Title: "Biblioteca de Plantillas",
    step9Body: "Guarda tus configuraciones actuales como plantillas para reutilizarlas r\u00e1pidamente. Carga plantillas para llenar marca, plataforma, tono y formato al instante.",
    completeTitle: "\u00a1Todo Listo!",
    completeBody: "Has visto generaci\u00f3n de contenido real, variantes A/B, el planificador de calendario y gesti\u00f3n de plantillas. Explora el historial, exporta como JSON o Markdown, y agrega tu clave API de Claude para generaci\u00f3n real con IA.",
    pagesVisited: "Features Exploradas",
    demosPlayed: "Acciones Reales",
    featuresExplored: "Pasos Completados",
    sampleBrand: "App de meditaci\u00f3n para profesionales con IA adaptativa que reduce el estr\u00e9s en 10 minutos al d\u00eda, con sesiones personalizadas y seguimiento de progreso",
    stepOf: (c, t) => `${c} / ${t}`,
  },
};
